// Code generated by pigeon; DO NOT EDIT.

package filterexpr

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	pjson "github.com/pinpt/go-common/v10/json"
)

const null = "null"

func toIfaceSlice(v interface{}) []interface{} {
	if v == nil {
		return nil
	}
	return v.([]interface{})
}

type Node struct {
	Key    string
	Value  string
	RegExp bool
	re     *regexp.Regexp
}

var _ Filter = (*Node)(nil)

func (n *Node) String() string {
	if n.RegExp {
		return fmt.Sprintf("Node[%s=~%s]", n.Key, n.Value)
	}
	return fmt.Sprintf("Node[%s=%s]", n.Key, n.Value)
}

func toString(val interface{}) string {
	if sval, ok := val.(string); ok {
		return sval
	}
	if sval, ok := val.(fmt.Stringer); ok {
		return sval.String()
	}
	return pjson.Stringify(val)
}

func (n *Node) matchVal(theval string, val interface{}, kv map[string]interface{}) bool {
	if kv, ok := val.([]string); ok {
		for i := 0; i < len(kv); i++ {
			if n.RegExp {
				if n.re.MatchString(kv[i]) {
					return true
				}
			} else if kv[i] == theval {
				return true
			}
		}
		return false
	}
	if kv, ok := val.([]interface{}); ok {
		for i := 0; i < len(kv); i++ {
			kval := toString(kv[i])
			if n.RegExp {
				if n.re.MatchString(kval) {
					return true
				}
			} else if kval == theval {
				return true
			}
		}
		return false
	}
	sval := toString(val)
	if n.RegExp {
		return n.re.MatchString(sval)
	}
	return theval == sval
}

func (n *Node) Test(kv map[string]interface{}) bool {
	val, ok := kv[n.Key]
	if ok {
		return n.matchVal(n.Value, val, kv)
	} else {
		if n.Value == null {
			return true
		}
	}
	if strings.Contains(n.Key, ".") {
		val, _ := pjson.DottedFind(n.Key, kv)
		if val == nil {
			tok := strings.Split(n.Key, ".")
			sval := kv[tok[0]]
			// looks like a string of JSON
			if s, ok := sval.(string); ok && s[0:1] == "{" && s[len(s)-1:] == "}" {
				svalkv := make(map[string]interface{})
				json.Unmarshal([]byte(s), &svalkv)
				val, _ = pjson.DottedFind(strings.Join(tok[1:], "."), svalkv)
			} else {
				return false
			}
		}
		return n.matchVal(n.Value, val, kv)
	}
	return n.Value == ""
}

type Expression struct {
	Left        *Node
	Conjunction string
	Right       *Expression
}

var _ Filter = (*Expression)(nil)

func (e *Expression) String() string {
	return fmt.Sprintf("Expression[%s,%s,%s]", e.Left, e.Conjunction, e.Right)
}

func (n *Expression) Test(kv map[string]interface{}) bool {
	if n.Right == nil {
		return n.Left.Test(kv)
	}
	if n.Conjunction == "OR" {
		return n.Left.Test(kv) || n.Right.Test(kv)
	}
	return n.Left.Test(kv) && n.Right.Test(kv)
}

type ExpressionGroup struct {
	Left        []*Expression
	Conjunction string
	Right       []*Expression
}

var _ Filter = (*ExpressionGroup)(nil)

func (g *ExpressionGroup) String() string {
	if g.Conjunction == "" {
		return fmt.Sprintf("ExpressionGroup[%s]", g.Left)
	}
	return fmt.Sprintf("ExpressionGroup[%s,%s,%s]", g.Left, g.Conjunction, g.Right)
}

func (n *ExpressionGroup) Test(kv map[string]interface{}) bool {
	if len(n.Right) == 0 {
		for _, e := range n.Left {
			if !e.Test(kv) {
				return false
			}
		}
		return true
	}
	left := true
	for _, e := range n.Left {
		if !e.Test(kv) {
			left = false
			break
		}
	}
	right := true
	for _, e := range n.Right {
		if !e.Test(kv) {
			right = false
			break
		}
	}
	if n.Conjunction == "OR" {
		return left || right
	}
	return left && right
}

type ExpressionList struct {
	groups []*ExpressionGroup
}

var _ Filter = (*ExpressionList)(nil)

func (l *ExpressionList) Test(kv map[string]interface{}) bool {
	var isOr bool
	for _, n := range l.groups {
		isOr = n.Conjunction == "OR"
		ok := n.Test(kv)
		if !ok {
			if isOr {
				continue
			}
			return false
		} else {
			if isOr {
				return true
			}
		}
	}
	return !isOr
}

func (l *ExpressionList) String() string {
	return fmt.Sprintf("ExpressionList[%s]", l.groups)
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Object",
			pos:  position{line: 206, col: 1, offset: 4612},
			expr: &actionExpr{
				pos: position{line: 206, col: 10, offset: 4623},
				run: (*parser).callonObject1,
				expr: &seqExpr{
					pos: position{line: 206, col: 10, offset: 4623},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 206, col: 10, offset: 4623},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 206, col: 12, offset: 4625},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 206, col: 16, offset: 4629},
								name: "ExpressionList",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 206, col: 31, offset: 4644},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 210, col: 1, offset: 4673},
			expr: &actionExpr{
				pos: position{line: 210, col: 9, offset: 4683},
				run: (*parser).callonValue1,
				expr: &seqExpr{
					pos: position{line: 210, col: 9, offset: 4683},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 210, col: 9, offset: 4683},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 210, col: 15, offset: 4689},
								name: "String",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 210, col: 24, offset: 4698},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "OrCondition",
			pos:  position{line: 214, col: 1, offset: 4725},
			expr: &litMatcher{
				pos:        position{line: 214, col: 15, offset: 4741},
				val:        "OR",
				ignoreCase: false,
				want:       "\"OR\"",
			},
		},
		{
			name: "AndCondition",
			pos:  position{line: 215, col: 1, offset: 4746},
			expr: &litMatcher{
				pos:        position{line: 215, col: 16, offset: 4763},
				val:        "AND",
				ignoreCase: false,
				want:       "\"AND\"",
			},
		},
		{
			name: "Condition",
			pos:  position{line: 217, col: 1, offset: 4770},
			expr: &choiceExpr{
				pos: position{line: 217, col: 13, offset: 4784},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 217, col: 13, offset: 4784},
						name: "OrCondition",
					},
					&ruleRefExpr{
						pos:  position{line: 217, col: 27, offset: 4798},
						name: "AndCondition",
					},
				},
			},
		},
		{
			name: "ExpressionList",
			pos:  position{line: 219, col: 1, offset: 4812},
			expr: &actionExpr{
				pos: position{line: 219, col: 18, offset: 4831},
				run: (*parser).callonExpressionList1,
				expr: &seqExpr{
					pos: position{line: 219, col: 18, offset: 4831},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 219, col: 18, offset: 4831},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 219, col: 20, offset: 4833},
							label: "vals",
							expr: &seqExpr{
								pos: position{line: 219, col: 27, offset: 4840},
								exprs: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 219, col: 27, offset: 4840},
										name: "ExpressionGroup",
									},
									&zeroOrMoreExpr{
										pos: position{line: 219, col: 43, offset: 4856},
										expr: &seqExpr{
											pos: position{line: 219, col: 45, offset: 4858},
											exprs: []interface{}{
												&ruleRefExpr{
													pos:  position{line: 219, col: 45, offset: 4858},
													name: "_",
												},
												&ruleRefExpr{
													pos:  position{line: 219, col: 47, offset: 4860},
													name: "Condition",
												},
												&ruleRefExpr{
													pos:  position{line: 219, col: 57, offset: 4870},
													name: "ExpressionGroup",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ExpressionGroup",
			pos:  position{line: 249, col: 1, offset: 5738},
			expr: &actionExpr{
				pos: position{line: 249, col: 19, offset: 5758},
				run: (*parser).callonExpressionGroup1,
				expr: &seqExpr{
					pos: position{line: 249, col: 19, offset: 5758},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 249, col: 19, offset: 5758},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 249, col: 21, offset: 5760},
							label: "vals",
							expr: &oneOrMoreExpr{
								pos: position{line: 249, col: 26, offset: 5765},
								expr: &seqExpr{
									pos: position{line: 249, col: 28, offset: 5767},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 249, col: 28, offset: 5767},
											name: "_",
										},
										&zeroOrOneExpr{
											pos: position{line: 249, col: 30, offset: 5769},
											expr: &ruleRefExpr{
												pos:  position{line: 249, col: 30, offset: 5769},
												name: "LeftParen",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 249, col: 41, offset: 5780},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 249, col: 43, offset: 5782},
											name: "Expression",
										},
										&ruleRefExpr{
											pos:  position{line: 249, col: 54, offset: 5793},
											name: "_",
										},
										&zeroOrOneExpr{
											pos: position{line: 249, col: 56, offset: 5795},
											expr: &ruleRefExpr{
												pos:  position{line: 249, col: 56, offset: 5795},
												name: "RightParen",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 249, col: 68, offset: 5807},
											name: "_",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Separator",
			pos:  position{line: 260, col: 1, offset: 6106},
			expr: &litMatcher{
				pos:        position{line: 260, col: 13, offset: 6120},
				val:        ":",
				ignoreCase: false,
				want:       "\":\"",
			},
		},
		{
			name: "NodeVal",
			pos:  position{line: 262, col: 1, offset: 6125},
			expr: &actionExpr{
				pos: position{line: 262, col: 11, offset: 6137},
				run: (*parser).callonNodeVal1,
				expr: &seqExpr{
					pos: position{line: 262, col: 11, offset: 6137},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 262, col: 11, offset: 6137},
							label: "val",
							expr: &choiceExpr{
								pos: position{line: 262, col: 17, offset: 6143},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 262, col: 17, offset: 6143},
										name: "String",
									},
									&ruleRefExpr{
										pos:  position{line: 262, col: 26, offset: 6152},
										name: "Number",
									},
									&ruleRefExpr{
										pos:  position{line: 262, col: 35, offset: 6161},
										name: "Bool",
									},
									&ruleRefExpr{
										pos:  position{line: 262, col: 42, offset: 6168},
										name: "Regexp",
									},
									&ruleRefExpr{
										pos:  position{line: 262, col: 51, offset: 6177},
										name: "Null",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 262, col: 58, offset: 6184},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Node",
			pos:  position{line: 266, col: 1, offset: 6211},
			expr: &actionExpr{
				pos: position{line: 266, col: 8, offset: 6220},
				run: (*parser).callonNode1,
				expr: &seqExpr{
					pos: position{line: 266, col: 8, offset: 6220},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 266, col: 8, offset: 6220},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 266, col: 10, offset: 6222},
							label: "vals",
							expr: &seqExpr{
								pos: position{line: 266, col: 17, offset: 6229},
								exprs: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 266, col: 17, offset: 6229},
										name: "_",
									},
									&ruleRefExpr{
										pos:  position{line: 266, col: 19, offset: 6231},
										name: "Label",
									},
									&ruleRefExpr{
										pos:  position{line: 266, col: 25, offset: 6237},
										name: "_",
									},
									&ruleRefExpr{
										pos:  position{line: 266, col: 27, offset: 6239},
										name: "Separator",
									},
									&ruleRefExpr{
										pos:  position{line: 266, col: 37, offset: 6249},
										name: "_",
									},
									&ruleRefExpr{
										pos:  position{line: 266, col: 39, offset: 6251},
										name: "NodeVal",
									},
									&ruleRefExpr{
										pos:  position{line: 266, col: 47, offset: 6259},
										name: "_",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Expression",
			pos:  position{line: 279, col: 1, offset: 6527},
			expr: &actionExpr{
				pos: position{line: 279, col: 14, offset: 6542},
				run: (*parser).callonExpression1,
				expr: &seqExpr{
					pos: position{line: 279, col: 14, offset: 6542},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 279, col: 14, offset: 6542},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 279, col: 16, offset: 6544},
							label: "vals",
							expr: &seqExpr{
								pos: position{line: 279, col: 23, offset: 6551},
								exprs: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 279, col: 23, offset: 6551},
										name: "Node",
									},
									&zeroOrMoreExpr{
										pos: position{line: 279, col: 28, offset: 6556},
										expr: &seqExpr{
											pos: position{line: 279, col: 30, offset: 6558},
											exprs: []interface{}{
												&ruleRefExpr{
													pos:  position{line: 279, col: 30, offset: 6558},
													name: "_",
												},
												&ruleRefExpr{
													pos:  position{line: 279, col: 32, offset: 6560},
													name: "Condition",
												},
												&ruleRefExpr{
													pos:  position{line: 279, col: 42, offset: 6570},
													name: "_",
												},
												&ruleRefExpr{
													pos:  position{line: 279, col: 44, offset: 6572},
													name: "Node",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Label",
			pos:  position{line: 308, col: 1, offset: 7470},
			expr: &actionExpr{
				pos: position{line: 308, col: 9, offset: 7480},
				run: (*parser).callonLabel1,
				expr: &oneOrMoreExpr{
					pos: position{line: 308, col: 11, offset: 7482},
					expr: &charClassMatcher{
						pos:        position{line: 308, col: 11, offset: 7482},
						val:        "[a-zA-Z0-9\\\\._\\\\-]",
						chars:      []rune{'\\', '.', '_', '\\', '-'},
						ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 312, col: 1, offset: 7540},
			expr: &actionExpr{
				pos: position{line: 312, col: 10, offset: 7551},
				run: (*parser).callonString1,
				expr: &seqExpr{
					pos: position{line: 312, col: 10, offset: 7551},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 312, col: 10, offset: 7551},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 312, col: 14, offset: 7555},
							expr: &choiceExpr{
								pos: position{line: 312, col: 16, offset: 7557},
								alternatives: []interface{}{
									&seqExpr{
										pos: position{line: 312, col: 16, offset: 7557},
										exprs: []interface{}{
											&notExpr{
												pos: position{line: 312, col: 16, offset: 7557},
												expr: &ruleRefExpr{
													pos:  position{line: 312, col: 17, offset: 7558},
													name: "EscapedChar",
												},
											},
											&anyMatcher{
												line: 312, col: 29, offset: 7570,
											},
										},
									},
									&seqExpr{
										pos: position{line: 312, col: 33, offset: 7574},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 312, col: 33, offset: 7574},
												val:        "\\",
												ignoreCase: false,
												want:       "\"\\\\\"",
											},
											&ruleRefExpr{
												pos:  position{line: 312, col: 38, offset: 7579},
												name: "EscapeSequence",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 312, col: 56, offset: 7597},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
					},
				},
			},
		},
		{
			name: "LeftParen",
			pos:  position{line: 317, col: 1, offset: 7715},
			expr: &litMatcher{
				pos:        position{line: 317, col: 13, offset: 7729},
				val:        "(",
				ignoreCase: false,
				want:       "\"(\"",
			},
		},
		{
			name: "RightParen",
			pos:  position{line: 319, col: 1, offset: 7734},
			expr: &litMatcher{
				pos:        position{line: 319, col: 14, offset: 7749},
				val:        ")",
				ignoreCase: false,
				want:       "\")\"",
			},
		},
		{
			name: "EscapedChar",
			pos:  position{line: 321, col: 1, offset: 7754},
			expr: &charClassMatcher{
				pos:        position{line: 321, col: 15, offset: 7770},
				val:        "[\\x00-\\x1f\"\\\\]",
				chars:      []rune{'"', '\\'},
				ranges:     []rune{'\x00', '\x1f'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EscapeSequence",
			pos:  position{line: 323, col: 1, offset: 7786},
			expr: &choiceExpr{
				pos: position{line: 323, col: 18, offset: 7805},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 323, col: 18, offset: 7805},
						name: "SingleCharEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 323, col: 37, offset: 7824},
						name: "UnicodeEscape",
					},
				},
			},
		},
		{
			name: "SingleCharEscape",
			pos:  position{line: 325, col: 1, offset: 7839},
			expr: &charClassMatcher{
				pos:        position{line: 325, col: 20, offset: 7860},
				val:        "[\"\\\\/bfnrt]",
				chars:      []rune{'"', '\\', '/', 'b', 'f', 'n', 'r', 't'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "UnicodeEscape",
			pos:  position{line: 327, col: 1, offset: 7873},
			expr: &seqExpr{
				pos: position{line: 327, col: 17, offset: 7891},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 327, col: 17, offset: 7891},
						val:        "u",
						ignoreCase: false,
						want:       "\"u\"",
					},
					&ruleRefExpr{
						pos:  position{line: 327, col: 21, offset: 7895},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 327, col: 30, offset: 7904},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 327, col: 39, offset: 7913},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 327, col: 48, offset: 7922},
						name: "HexDigit",
					},
				},
			},
		},
		{
			name: "DecimalDigit",
			pos:  position{line: 329, col: 1, offset: 7932},
			expr: &charClassMatcher{
				pos:        position{line: 329, col: 16, offset: 7949},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "NonZeroDecimalDigit",
			pos:  position{line: 331, col: 1, offset: 7956},
			expr: &charClassMatcher{
				pos:        position{line: 331, col: 23, offset: 7980},
				val:        "[1-9]",
				ranges:     []rune{'1', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Number",
			pos:  position{line: 333, col: 1, offset: 7987},
			expr: &actionExpr{
				pos: position{line: 333, col: 10, offset: 7998},
				run: (*parser).callonNumber1,
				expr: &seqExpr{
					pos: position{line: 333, col: 10, offset: 7998},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 333, col: 10, offset: 7998},
							expr: &litMatcher{
								pos:        position{line: 333, col: 10, offset: 7998},
								val:        "-",
								ignoreCase: false,
								want:       "\"-\"",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 333, col: 15, offset: 8003},
							name: "Integer",
						},
						&zeroOrOneExpr{
							pos: position{line: 333, col: 23, offset: 8011},
							expr: &seqExpr{
								pos: position{line: 333, col: 25, offset: 8013},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 333, col: 25, offset: 8013},
										val:        ".",
										ignoreCase: false,
										want:       "\".\"",
									},
									&oneOrMoreExpr{
										pos: position{line: 333, col: 29, offset: 8017},
										expr: &ruleRefExpr{
											pos:  position{line: 333, col: 29, offset: 8017},
											name: "DecimalDigit",
										},
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 333, col: 46, offset: 8034},
							expr: &ruleRefExpr{
								pos:  position{line: 333, col: 46, offset: 8034},
								name: "Exponent",
							},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 337, col: 1, offset: 8099},
			expr: &choiceExpr{
				pos: position{line: 337, col: 11, offset: 8111},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 337, col: 11, offset: 8111},
						val:        "0",
						ignoreCase: false,
						want:       "\"0\"",
					},
					&seqExpr{
						pos: position{line: 337, col: 17, offset: 8117},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 337, col: 17, offset: 8117},
								name: "NonZeroDecimalDigit",
							},
							&zeroOrMoreExpr{
								pos: position{line: 337, col: 37, offset: 8137},
								expr: &ruleRefExpr{
									pos:  position{line: 337, col: 37, offset: 8137},
									name: "DecimalDigit",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Exponent",
			pos:  position{line: 339, col: 1, offset: 8152},
			expr: &seqExpr{
				pos: position{line: 339, col: 12, offset: 8165},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 339, col: 12, offset: 8165},
						val:        "e",
						ignoreCase: true,
						want:       "\"e\"i",
					},
					&zeroOrOneExpr{
						pos: position{line: 339, col: 17, offset: 8170},
						expr: &charClassMatcher{
							pos:        position{line: 339, col: 17, offset: 8170},
							val:        "[+-]",
							chars:      []rune{'+', '-'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&oneOrMoreExpr{
						pos: position{line: 339, col: 23, offset: 8176},
						expr: &ruleRefExpr{
							pos:  position{line: 339, col: 23, offset: 8176},
							name: "DecimalDigit",
						},
					},
				},
			},
		},
		{
			name: "Bool",
			pos:  position{line: 341, col: 1, offset: 8191},
			expr: &choiceExpr{
				pos: position{line: 341, col: 8, offset: 8200},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 341, col: 8, offset: 8200},
						run: (*parser).callonBool2,
						expr: &litMatcher{
							pos:        position{line: 341, col: 8, offset: 8200},
							val:        "true",
							ignoreCase: false,
							want:       "\"true\"",
						},
					},
					&actionExpr{
						pos: position{line: 341, col: 38, offset: 8230},
						run: (*parser).callonBool4,
						expr: &litMatcher{
							pos:        position{line: 341, col: 38, offset: 8230},
							val:        "false",
							ignoreCase: false,
							want:       "\"false\"",
						},
					},
				},
			},
		},
		{
			name: "HexDigit",
			pos:  position{line: 343, col: 1, offset: 8261},
			expr: &charClassMatcher{
				pos:        position{line: 343, col: 12, offset: 8274},
				val:        "[0-9a-f]i",
				ranges:     []rune{'0', '9', 'a', 'f'},
				ignoreCase: true,
				inverted:   false,
			},
		},
		{
			name: "Regexp",
			pos:  position{line: 345, col: 1, offset: 8285},
			expr: &actionExpr{
				pos: position{line: 345, col: 10, offset: 8296},
				run: (*parser).callonRegexp1,
				expr: &seqExpr{
					pos: position{line: 345, col: 10, offset: 8296},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 345, col: 10, offset: 8296},
							val:        "/",
							ignoreCase: false,
							want:       "\"/\"",
						},
						&oneOrMoreExpr{
							pos: position{line: 345, col: 14, offset: 8300},
							expr: &charClassMatcher{
								pos:        position{line: 345, col: 14, offset: 8300},
								val:        "[A-Za-z0-9^$-._\\\\(\\\\)\\\\?\\\\+{} ]",
								chars:      []rune{'^', '_', '\\', '(', '\\', ')', '\\', '?', '\\', '+', '{', '}', ' '},
								ranges:     []rune{'A', 'Z', 'a', 'z', '0', '9', '$', '.'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&litMatcher{
							pos:        position{line: 345, col: 47, offset: 8333},
							val:        "/",
							ignoreCase: false,
							want:       "\"/\"",
						},
					},
				},
			},
		},
		{
			name: "Null",
			pos:  position{line: 349, col: 1, offset: 8402},
			expr: &actionExpr{
				pos: position{line: 349, col: 8, offset: 8411},
				run: (*parser).callonNull1,
				expr: &litMatcher{
					pos:        position{line: 349, col: 8, offset: 8411},
					val:        "null",
					ignoreCase: false,
					want:       "\"null\"",
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 353, col: 1, offset: 8444},
			expr: &zeroOrMoreExpr{
				pos: position{line: 353, col: 18, offset: 8463},
				expr: &charClassMatcher{
					pos:        position{line: 353, col: 18, offset: 8463},
					val:        "[ \\t\\r\\n]",
					chars:      []rune{' ', '\t', '\r', '\n'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 355, col: 1, offset: 8475},
			expr: &notExpr{
				pos: position{line: 355, col: 7, offset: 8483},
				expr: &anyMatcher{
					line: 355, col: 8, offset: 8484,
				},
			},
		},
	},
}

func (c *current) onObject1(val interface{}) (interface{}, error) {
	return val, nil
}

func (p *parser) callonObject1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onObject1(stack["val"])
}

func (c *current) onValue1(val interface{}) (interface{}, error) {
	return val, nil
}

func (p *parser) callonValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue1(stack["val"])
}

func (c *current) onExpressionList1(vals interface{}) (interface{}, error) {
	valsSl := toIfaceSlice(vals)
	res := &ExpressionList{
		groups: make([]*ExpressionGroup, 0),
	}
	left := valsSl[0].([]*Expression)
	initial := &ExpressionGroup{
		Left: left,
	}
	res.groups = append(res.groups, initial)
	right := valsSl[1].([]interface{})
	for _, e := range right {
		conjunction := string(e.([]interface{})[1].([]byte))
		if initial.Conjunction == "" {
			initial.Conjunction = conjunction
		}
		nodeRight := e.([]interface{})[2].([]*Expression)
		if initial.Right == nil {
			initial.Right = nodeRight
		} else {
			initial = &ExpressionGroup{
				Left:        nodeRight,
				Conjunction: conjunction,
			}
			res.groups = append(res.groups, initial)
		}
	}
	return res, nil
}

func (p *parser) callonExpressionList1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpressionList1(stack["vals"])
}

func (c *current) onExpressionGroup1(vals interface{}) (interface{}, error) {
	valsSl := toIfaceSlice(vals)
	res := make([]*Expression, 0)
	//fmt.Println("expression group", len(valsSl))
	for _, val := range valsSl {
		//fmt.Println("exp group", i, "val", val)
		res = append(res, toIfaceSlice(val)[3].(*Expression))
	}
	return res, nil
}

func (p *parser) callonExpressionGroup1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpressionGroup1(stack["vals"])
}

func (c *current) onNodeVal1(val interface{}) (interface{}, error) {
	return val, nil
}

func (p *parser) callonNodeVal1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNodeVal1(stack["val"])
}

func (c *current) onNode1(vals interface{}) (interface{}, error) {
	var res Node
	valsSl := toIfaceSlice(vals)
	res.Key = valsSl[1].(string)
	if re, ok := valsSl[5].(*regexp.Regexp); ok {
		res.re = re
		res.RegExp = true
	} else {
		res.Value = toString(valsSl[5])
	}
	return &res, nil
}

func (p *parser) callonNode1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNode1(stack["vals"])
}

func (c *current) onExpression1(vals interface{}) (interface{}, error) {
	valsSl := toIfaceSlice(vals)
	left := valsSl[0].(*Node)
	var right *Expression
	var current *Expression
	var conjunction string
	//fmt.Println("len", len(valsSl))
	if len(valsSl) > 1 {
		grouping := toIfaceSlice(valsSl[1])
		for _, group := range grouping {
			igroup := toIfaceSlice(group)
			//fmt.Println(i, "group", igroup)
			conjunction = string(igroup[1].([]byte))
			//fmt.Println(i, conjunction)
			iright := igroup[3].(*Node)
			//fmt.Println(i, iright)
			newexp := &Expression{iright, conjunction, nil}
			if right == nil {
				right = newexp
				current = newexp
			} else {
				current.Right = newexp
				current = newexp
			}
		}
	}
	return &Expression{left, conjunction, right}, nil
}

func (p *parser) callonExpression1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpression1(stack["vals"])
}

func (c *current) onLabel1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonLabel1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLabel1()
}

func (c *current) onString1() (interface{}, error) {
	c.text = bytes.Replace(c.text, []byte(`\/`), []byte(`/`), -1)
	return strconv.Unquote(string(c.text))
}

func (p *parser) callonString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString1()
}

func (c *current) onNumber1() (interface{}, error) {
	return strconv.ParseFloat(string(c.text), 64)
}

func (p *parser) callonNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

func (c *current) onBool2() (interface{}, error) {
	return true, nil
}

func (p *parser) callonBool2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBool2()
}

func (c *current) onBool4() (interface{}, error) {
	return false, nil
}

func (p *parser) callonBool4() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBool4()
}

func (c *current) onRegexp1() (interface{}, error) {
	return regexp.Compile(string(c.text[1 : len(c.text)-1]))
}

func (p *parser) callonRegexp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRegexp1()
}

func (c *current) onNull1() (interface{}, error) {
	return null, nil
}

func (p *parser) callonNull1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNull1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
